using System.Text;

namespace Flare.ApiDocGen;

/// <summary>Emits the generated <c>ComponentApiRegistry</c> C# source consumed by Flare.Gallery.</summary>
internal static class RegistryEmitter
{
    public static string Emit(IReadOnlyList<ComponentDoc> components, IReadOnlyList<EnumDoc> enums)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by tools/Flare.ApiDocGen. Do not edit by hand.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine("namespace Flare.Gallery.Api;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>Auto-generated registry of Flare component and type API documentation.</summary>");
        sb.AppendLine("public static class ComponentApiRegistry");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>All documented components keyed by type name (e.g. \"FlareButton\").</summary>");
        sb.AppendLine("    public static IReadOnlyDictionary<string, ApiComponentInfo> Components { get; } = Build();");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>All documented enums keyed by type name (e.g. \"FlareColor\").</summary>");
        sb.AppendLine("    public static IReadOnlyDictionary<string, ApiEnumInfo> Enums { get; } = BuildEnums();");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Returns the documentation for a component, or null when unknown.</summary>");
        sb.AppendLine("    public static ApiComponentInfo? Get(string componentName) =>");
        sb.AppendLine("        Components.TryGetValue(componentName, out var info) ? info : null;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Returns the documentation for an enum, or null when unknown.</summary>");
        sb.AppendLine("    public static ApiEnumInfo? GetEnum(string typeName) =>");
        sb.AppendLine("        Enums.TryGetValue(typeName, out var info) ? info : null;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>True when a type name has a documentation page (component or enum).</summary>");
        sb.AppendLine("    public static bool IsDocumented(string typeName) =>");
        sb.AppendLine("        Components.ContainsKey(typeName) || Enums.ContainsKey(typeName);");
        sb.AppendLine();
        sb.AppendLine("    private static Dictionary<string, ApiComponentInfo> Build()");
        sb.AppendLine("    {");
        sb.AppendLine("        var c = new Dictionary<string, ApiComponentInfo>(System.StringComparer.Ordinal);");
        sb.AppendLine();

        foreach (var component in components.OrderBy(x => x.Name, StringComparer.Ordinal))
            EmitComponent(sb, component);

        sb.AppendLine("        return c;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static Dictionary<string, ApiEnumInfo> BuildEnums()");
        sb.AppendLine("    {");
        sb.AppendLine("        var e = new Dictionary<string, ApiEnumInfo>(System.StringComparer.Ordinal);");
        sb.AppendLine();

        foreach (var enumDoc in enums.OrderBy(x => x.Name, StringComparer.Ordinal))
            EmitEnum(sb, enumDoc);

        sb.AppendLine("        return e;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitEnum(StringBuilder sb, EnumDoc enumDoc)
    {
        sb.AppendLine($"        e[{Lit(enumDoc.Name)}] = new ApiEnumInfo(");
        sb.AppendLine($"            {Lit(enumDoc.Name)},");
        sb.AppendLine($"            {Lit(enumDoc.FullName)},");
        sb.AppendLine($"            {Lit(enumDoc.Namespace)},");
        sb.AppendLine($"            {Lit(enumDoc.Summary)},");
        sb.AppendLine($"            {Lit(enumDoc.Remarks)},");
        if (enumDoc.Members.Count == 0)
        {
            sb.AppendLine("            System.Array.Empty<ApiEnumMember>(),");
        }
        else
        {
            sb.AppendLine("            new ApiEnumMember[]");
            sb.AppendLine("            {");
            foreach (var m in enumDoc.Members)
                sb.AppendLine($"                new ApiEnumMember({Lit(m.Name)}, {Lit(m.Value)}, {Lit(m.Summary)}),");
            sb.AppendLine("            },");
        }

        if (enumDoc.UsedBy.Count == 0)
        {
            sb.AppendLine("            System.Array.Empty<string>());");
        }
        else
        {
            sb.AppendLine("            new string[]");
            sb.AppendLine("            {");
            foreach (var user in enumDoc.UsedBy)
                sb.AppendLine($"                {Lit(user)},");
            sb.AppendLine("            });");
        }
        sb.AppendLine();
    }

    private static void EmitComponent(StringBuilder sb, ComponentDoc component)
    {
        sb.AppendLine($"        c[{Lit(component.Name)}] = new ApiComponentInfo(");
        sb.AppendLine($"            {Lit(component.Name)},");
        sb.AppendLine($"            {Lit(component.FullName)},");
        sb.AppendLine($"            {Lit(component.Namespace)},");
        sb.AppendLine($"            {Lit(component.Summary)},");
        sb.AppendLine($"            {Lit(component.Remarks)},");
        EmitParameters(sb, component.Parameters);
        EmitMethods(sb, component.Methods);
        EmitStringArray(sb, component.Inherits, trailingComma: true);
        EmitStringArray(sb, component.DerivedBy, trailingComma: false);
        sb.AppendLine("            );");
        sb.AppendLine();
    }

    private static void EmitStringArray(StringBuilder sb, IReadOnlyList<string> values, bool trailingComma)
    {
        var tail = trailingComma ? "," : string.Empty;
        if (values.Count == 0)
        {
            sb.AppendLine($"            System.Array.Empty<string>(){tail}");
            return;
        }

        sb.AppendLine("            new string[]");
        sb.AppendLine("            {");
        foreach (var value in values)
            sb.AppendLine($"                {Lit(value)},");
        sb.AppendLine($"            }}{tail}");
    }

    private static void EmitParameters(StringBuilder sb, IReadOnlyList<ParameterDoc> parameters)
    {
        if (parameters.Count == 0)
        {
            sb.AppendLine("            System.Array.Empty<ApiParameterInfo>(),");
            return;
        }

        sb.AppendLine("            new ApiParameterInfo[]");
        sb.AppendLine("            {");
        foreach (var p in parameters)
        {
            sb.AppendLine("                new ApiParameterInfo(" +
                $"{Lit(p.Name)}, {Lit(p.Type)}, {Lit(p.Default)}, {Lit(p.Summary)}, {Lit(p.Remarks)}, " +
                $"{Bool(p.IsCascading)}, {Bool(p.IsEventCallback)}, {Bool(p.IsRequired)}, {Lit(p.DeclaringType)}),");
        }
        sb.AppendLine("            },");
    }

    private static void EmitMethods(StringBuilder sb, IReadOnlyList<MethodDoc> methods)
    {
        if (methods.Count == 0)
        {
            sb.AppendLine("            System.Array.Empty<ApiMethodInfo>(),");
            return;
        }

        sb.AppendLine("            new ApiMethodInfo[]");
        sb.AppendLine("            {");
        foreach (var m in methods)
        {
            sb.AppendLine("                new ApiMethodInfo(" +
                $"{Lit(m.Name)}, {Lit(m.Signature)}, {Lit(m.ReturnType)}, {Lit(m.ReturnSummary)}, {Lit(m.Summary)},");
            if (m.Parameters.Count == 0)
            {
                sb.AppendLine("                    System.Array.Empty<ApiMethodParameter>()),");
            }
            else
            {
                sb.AppendLine("                    new ApiMethodParameter[]");
                sb.AppendLine("                    {");
                foreach (var mp in m.Parameters)
                    sb.AppendLine($"                        new ApiMethodParameter({Lit(mp.Name)}, {Lit(mp.Type)}, {Lit(mp.Summary)}),");
                sb.AppendLine("                    }),");
            }
        }
        sb.AppendLine("            },");
    }

    private static string Bool(bool value) => value ? "true" : "false";

    /// <summary>Renders a C# verbatim string literal, or <c>null</c> for missing values.</summary>
    private static string Lit(string? value)
    {
        if (value is null)
            return "null";
        return "@\"" + value.Replace("\"", "\"\"") + "\"";
    }
}
