namespace Flare.Components.Tests;

// The MaterialDesign3.Svg add-on ships the Material Symbols (rounded) set as inline-SVG FlareSvgIcon values
// (generated by tools/MaterialSymbolsGen). The catalog is authored on the 960 grid, and both fill variants
// drop into any FlareIcon-typed slot.
public class MaterialDesign3IconsTests : FlareTestContext
{
    [Fact]
    public void RegularIcon_RendersSvgPath_On960Grid()
    {
        var cut = Render<FlareIconView>(p => p.Add(x => x.Value, MaterialDesign3Icons.Regular.Home));

        var svg = cut.Find("svg");
        Assert.Equal("0 -960 960 960", svg.GetAttribute("viewBox"));
        Assert.NotEmpty(cut.FindAll("svg path"));
    }

    [Fact]
    public void FilledDiffersFromRegular()
    {
        Assert.NotEqual(MaterialDesign3Icons.Regular.Home.Data, MaterialDesign3Icons.Filled.Home.Data);
    }

    [Fact]
    public void FlowsIntoFlareIconButton_AsFlareIcon()
    {
        var cut = Render<FlareIconButton>(p => p
            .Add(x => x.Icon, MaterialDesign3Icons.Filled.Settings)
            .Add(x => x.AriaLabel, "Settings"));

        Assert.NotEmpty(cut.FindAll("svg path"));
    }
}
