// Build-time generator: reads MudBlazor's Material Icons (Filled) SVG constants and emits a MaterialIcons
// catalog of FlareSvgIcon values for Flare.Icons.MaterialDesign2.Svg. Material Icons are Apache-2.0.
// Run: node tools/MaterialIconGen/gen.mjs
import fs from 'fs';

const REPO = 'C:/Job/Projects/FrigaT/Flare';
const src = fs.readFileSync('C:/Job/Projects/GitHub/MudBlazor/src/MudBlazor/Icons/Material/Filled.cs', 'utf8');

// public const string Name = "....";  (value uses \" escapes)
const re = /public const string (\w+) = "((?:\\.|[^"\\])*)";/g;
const icons = [];
let m;
while ((m = re.exec(src))) {
  const name = m[1];
  // Unescape the C# string literal to the real SVG markup.
  const svg = m[2].replace(/\\"/g, '"').replace(/\\\\/g, '\\');
  // Skip anything containing a raw triple-quote run (would break the C# raw string literal). None expected.
  if (svg.includes('"""')) continue;
  icons.push({ name, svg });
}
icons.sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));

let out = '';
out += '// <auto-generated />\n';
out += '// Generated by tools/MaterialIconGen from the Material Icons set (Apache License 2.0).\n';
out += '// Re-run the generator to refresh. See the repository NOTICE.\n\n';
out += 'namespace Flare.Components;\n\n';
out += '/// <summary>\n';
out += '/// The Material Design 2 (Material Icons, filled) set as ready <see cref="FlareSvgIcon"/> values -\n';
out += '/// inline SVG, no icon font. Use anywhere a <see cref="FlareIcon"/> is accepted, e.g.\n';
out += '/// <c>&lt;FlareIconButton Icon="@MaterialIcons.Home" /&gt;</c>.\n';
out += '/// </summary>\n';
out += 'public static class MaterialIcons\n';
out += '{\n';
for (const { name, svg } of icons) {
  out += `    /// <summary>The Material <c>${name}</c> icon.</summary>\n`;
  out += `    public static FlareSvgIcon ${name} => new() { Data = """${svg}""" };\n`;
}
out += '}\n';

const outPath = REPO + '/src/Flare.Icons.MaterialDesign2.Svg/MaterialIcons.g.cs';
fs.writeFileSync(outPath, out, 'utf8');
console.log('icons:', icons.length, '-> wrote', outPath);
