using Flare.Abstractions.Tokens;

namespace Flare.Abstractions;

/// <summary>Injects the active theme's CSS custom properties into the document.</summary>
public interface ICssVariableInjector
{
    /// <summary>Writes the composed design + color tokens as CSS custom properties on :root via
    /// JS interop (Inject strategy).</summary>
    ValueTask InjectAsync(DesignTokens design, ColorScheme colors, CancellationToken ct = default);

    /// <summary>
    /// Replaces the static, class-scoped theme stylesheet (ClassToggle strategy). The CSS is
    /// generated by <c>TokensToCss</c> and applied once; switching is then a class swap.
    /// </summary>
    ValueTask SetStaticCssAsync(string css, CancellationToken ct = default);

    /// <summary>Sets one or more CSS custom properties on :root via JS interop.</summary>
    ValueTask SetCustomTokensAsync(IReadOnlyDictionary<string, string> tokens, CancellationToken ct = default);

    /// <summary>Removes one or more CSS custom properties from :root via JS interop.</summary>
    ValueTask ClearCustomTokensAsync(IEnumerable<string> tokenNames, CancellationToken ct = default);
}
