using System.Text;
using Flare.Tools.Md2SpecParser.Configuration;
using Flare.Tools.Md2SpecParser.Downloading;
using Flare.Tools.Md2SpecParser.Parsing;

namespace Flare.Tools.Md2SpecParser.Generation;

/// <summary>Downloads the configured pages and writes one markdown file per type.</summary>
public sealed class SpecWriter(Md2Config config, HttpClient http, SiteMetaIndex index)
{
    /// <summary>What happened to one page.</summary>
    /// <param name="Type">The configured type.</param>
    /// <param name="Status">written / skipped / failed.</param>
    /// <param name="Detail">Output path, or the reason it did not get one.</param>
    public sealed record Result(string Type, string Status, string Detail);

    /// <summary>Generates the given pages; an unresolved route fails that page and no other.</summary>
    public async Task<IReadOnlyList<Result>> GenerateAsync(IEnumerable<Md2Page> pages, CancellationToken ct = default)
    {
        var results = new List<Result>();
        foreach (var page in pages)
        {
            try
            {
                results.Add(await GenerateOneAsync(page, ct));
            }
            catch (Exception ex)
            {
                results.Add(new Result(page.Type, "failed", ex.Message));
            }
        }
        return results;
    }

    private async Task<Result> GenerateOneAsync(Md2Page page, CancellationToken ct)
    {
        if (page.Routes.Count == 0)
            return new Result(page.Type, "skipped", "no routes configured");

        var sb = new StringBuilder();
        sb.Append("# ").Append(page.Type).Append(" - Material Design 2\n");
        sb.Append("\nGenerated by `tools/Md2SpecParser` from m2.material.io page data. Do not hand-edit.\n");

        foreach (var route in page.Routes)
        {
            var path = index.PageDataPath(route)
                ?? throw new InvalidOperationException($"route not in the site index: {route}");

            var json = await http.GetStringAsync(config.BaseUrl.TrimEnd('/') + path, ct);
            sb.Append('\n').Append(GuidelineParser.ToMarkdown(json, route));
        }

        var dir = Path.Combine(config.OutputRoot, page.ResolveFolder());
        Directory.CreateDirectory(dir);
        var file = Path.Combine(dir, config.OutputFileName);
        await File.WriteAllTextAsync(file, sb.ToString(), ct);

        return new Result(page.Type, "written", file);
    }
}
