using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace Flare.Theming.Generators;

/// <summary>
/// Writes <c>CssVarMap.FlattenAttributed</c>: one assignment for every string token property that carries
/// <c>[CssVar]</c> and is reachable from <c>DesignTokens</c>. The attribute already names the variable a property
/// populates, so the table is derived from it rather than kept by hand - a new token reaches the browser the moment
/// its record property is declared, and a table row can no longer be forgotten.
/// </summary>
[Generator]
public sealed class CssVarMapGenerator : IIncrementalGenerator
{
    private const string TargetType = "Flare.Theming.CssVarMap";
    private const string TokensRoot = "Flare.Abstractions.Tokens.DesignTokens";
    private const string AttributeType = "Flare.Css.CssVarAttribute";
    private const string TokenNamespace = "Flare.Abstractions.Tokens";

    private static readonly DiagnosticDescriptor DuplicateName = new(
        id: "FLARE0001",
        title: "Two token properties write the same CSS variable",
        messageFormat: "CSS variable '{0}' is written by both t.{1} and t.{2}; one of them would silently overwrite the other",
        category: "Flare.Theming",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var model = context.CompilationProvider.Select(static (c, ct) => Build(c, ct));
        context.RegisterSourceOutput(model, static (spc, m) =>
        {
            if (m is null) return;
            foreach (var d in m.Diagnostics) spc.ReportDiagnostic(d);
            spc.AddSource("CssVarMap.Attributed.g.cs", SourceText.From(m.Source, Encoding.UTF8));
        });
    }

    private sealed class Model(string source, List<Diagnostic> diagnostics)
    {
        public string Source { get; } = source;
        public List<Diagnostic> Diagnostics { get; } = diagnostics;
    }

    private static Model? Build(Compilation c, CancellationToken ct)
    {
        if (c.GetTypeByMetadataName(TargetType) is null) return null;
        var root = c.GetTypeByMetadataName(TokensRoot);
        var attribute = c.GetTypeByMetadataName(AttributeType);
        if (root is null || attribute is null) return null;

        var constants = IndexConstants(c.GlobalNamespace);
        var rows = new List<(string Name, string Path)>();
        var firstPath = new Dictionary<string, string>(System.StringComparer.Ordinal);
        var diagnostics = new List<Diagnostic>();

        Walk(root, "", new HashSet<ITypeSymbol>(SymbolEqualityComparer.Default), attribute, rows, ct);

        foreach (var (name, path) in rows)
        {
            if (firstPath.TryGetValue(name, out var earlier))
                diagnostics.Add(Diagnostic.Create(DuplicateName, Location.None, name, earlier, path));
            else
                firstPath[name] = path;
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by Flare.Theming.Generators.CssVarMapGenerator from the [CssVar] attributes on the token records.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("namespace Flare.Theming;");
        sb.AppendLine();
        sb.AppendLine("public static partial class CssVarMap");
        sb.AppendLine("{");
        sb.AppendLine("    private static void FlattenAttributed(global::System.Collections.Generic.Dictionary<string, string> v, global::Flare.Abstractions.Tokens.DesignTokens t)");
        sb.AppendLine("    {");
        foreach (var (name, path) in rows)
        {
            var key = constants.TryGetValue(name, out var constant)
                ? constant
                : SymbolDisplay.FormatLiteral(name, quote: true);
            sb.Append("        v[").Append(key).Append("] = t.").Append(path).AppendLine(";");
        }
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return new Model(sb.ToString(), diagnostics);
    }

    // Depth-first over the token records in declaration order, so the table reads in the same order as the records.
    // The set holds the records on the current path only: a record type may appear under several parents, but may
    // not contain itself.
    private static void Walk(ITypeSymbol type, string prefix, HashSet<ITypeSymbol> onPath, INamedTypeSymbol attribute,
        List<(string Name, string Path)> rows, CancellationToken ct)
    {
        ct.ThrowIfCancellationRequested();
        if (!onPath.Add(type)) return;

        foreach (var property in type.GetMembers().OfType<IPropertySymbol>())
        {
            if (property.IsStatic || property.IsIndexer || property.DeclaredAccessibility != Accessibility.Public
                || property.GetMethod is null)
                continue;

            var path = prefix.Length == 0 ? property.Name : prefix + "." + property.Name;
            if (property.Type.SpecialType == SpecialType.System_String)
            {
                var data = property.GetAttributes().FirstOrDefault(a =>
                    SymbolEqualityComparer.Default.Equals(a.AttributeClass, attribute));
                if (data is { ConstructorArguments.Length: 1 } && data.ConstructorArguments[0].Value is string name)
                    rows.Add((name, path));
            }
            else if (property.Type is INamedTypeSymbol { TypeKind: TypeKind.Class } record
                     && record.ContainingNamespace.ToDisplayString().StartsWith(TokenNamespace, System.StringComparison.Ordinal))
            {
                Walk(record, path, onPath, attribute, rows, ct);
            }
        }

        onPath.Remove(type);
    }

    // Maps each registered variable name to the Flare.Css.Tokens constant that spells it, so the generated table
    // points at the registry rather than repeating the strings.
    private static Dictionary<string, string> IndexConstants(INamespaceSymbol global)
    {
        var map = new Dictionary<string, string>(System.StringComparer.Ordinal);
        var ns = global.GetNamespaceMembers().FirstOrDefault(n => n.Name == "Flare")?
            .GetNamespaceMembers().FirstOrDefault(n => n.Name == "Css")?
            .GetNamespaceMembers().FirstOrDefault(n => n.Name == "Tokens");
        if (ns is null) return map;

        var types = new Stack<INamedTypeSymbol>(ns.GetTypeMembers().OrderByDescending(t => t.Name, System.StringComparer.Ordinal));
        while (types.Count > 0)
        {
            var type = types.Pop();
            foreach (var field in type.GetMembers().OfType<IFieldSymbol>())
            {
                if (field.IsConst && field.DeclaredAccessibility == Accessibility.Public
                    && field.ConstantValue is string value && !map.ContainsKey(value))
                    map[value] = "global::" + field.ToDisplayString();
            }
            foreach (var nested in type.GetTypeMembers().OrderByDescending(t => t.Name, System.StringComparer.Ordinal))
                types.Push(nested);
        }
        return map;
    }
}
