using System.Reflection;
using System.Text;

// Generates a curated FluentIcons catalog for Flare.Icons.Fluent from the real Microsoft Fluent UI System
// Icons package (Regular + Filled, Size24). Over-list names freely: any not present in a variant is skipped
// and reported, so the output only contains icons that genuinely exist.

// A generous curated set of common UI icons (Fluent PascalCase names).
string[] names =
[
    "Home", "Search", "Settings", "Person", "PersonAdd", "People", "Mail", "MailRead", "Calendar",
    "CalendarLtr", "Clock", "Document", "DocumentText", "Folder", "FolderOpen", "Delete", "Edit", "Add",
    "Subtract", "Dismiss", "DismissCircle", "Checkmark", "CheckmarkCircle", "ChevronRight", "ChevronLeft",
    "ChevronUp", "ChevronDown", "ArrowRight", "ArrowLeft", "ArrowUp", "ArrowDown", "ArrowSync",
    "ArrowSort", "ArrowSortUp", "ArrowSortDown", "MoreHorizontal", "MoreVertical", "Save", "Print", "Share",
    "Copy", "Cut", "ClipboardPaste", "Filter", "Star", "Heart", "Warning", "Info", "ErrorCircle", "Eye",
    "EyeOff", "LockClosed", "LockOpen", "Alert", "Chat", "Call", "Camera", "Image", "Attach", "Link",
    "Cloud", "Wifi1", "Play", "Pause", "Stop", "Navigation", "Grid", "List", "Apps", "Emoji", "ThumbLike",
    "ThumbDislike", "Bookmark", "Flag", "Pin", "Location", "Cart", "Gift", "Wrench", "Bug", "Send",
    "Bookmark", "Globe", "Password", "SignOut", "Money", "Color", "TextBold", "TextItalic", "TextUnderline",
];
names = names.Distinct().ToArray();

var regularAsm = typeof(Microsoft.FluentUI.AspNetCore.Components.Icons.Regular.Size24.Home).Assembly;
var filledAsm = typeof(Microsoft.FluentUI.AspNetCore.Components.Icons.Filled.Size24.Home).Assembly;

const string regularPrefix = "Microsoft.FluentUI.AspNetCore.Components.Icons.Regular.Size24+";
const string filledPrefix = "Microsoft.FluentUI.AspNetCore.Components.Icons.Filled.Size24+";

string? Svg(Assembly asm, string prefix, string name)
{
    var t = asm.GetType(prefix + name);
    if (t is null) return null;
    var inst = Activator.CreateInstance(t)!;
    return (string?)t.GetProperty("Content")!.GetValue(inst);
}

var regular = new List<(string Name, string Svg)>();
var filled = new List<(string Name, string Svg)>();
var missing = new List<string>();

foreach (var name in names.OrderBy(n => n))
{
    var r = Svg(regularAsm, regularPrefix, name);
    var f = Svg(filledAsm, filledPrefix, name);
    if (r is null && f is null) { missing.Add(name); continue; }
    if (r is not null) regular.Add((name, r));
    if (f is not null) filled.Add((name, f));
}

var sb = new StringBuilder();
sb.AppendLine("// <auto-generated />");
sb.AppendLine("// Generated by tools/FluentIconGen from Microsoft.FluentUI.AspNetCore.Components.Icons (Size24).");
sb.AppendLine("// Fluent UI System Icons are (c) Microsoft, MIT licensed. Re-run the tool to refresh/extend.");
sb.AppendLine();
sb.AppendLine("namespace Flare.Components;");
sb.AppendLine();
sb.AppendLine("/// <summary>");
sb.AppendLine("/// A curated set of common Fluent UI System Icons (Size 24), ready as <see cref=\"FlareFluentIcon\"/>");
sb.AppendLine("/// values. Use anywhere a <see cref=\"FlareIcon\"/> is accepted, e.g.");
sb.AppendLine("/// <c>&lt;FlareIconButton Icon=\"@FluentIcons.Regular.Home\" /&gt;</c>. For icons not in this set, pass the");
sb.AppendLine("/// SVG path from the Fluent assets directly via <see cref=\"FlareFluentIcon.Data\"/>.");
sb.AppendLine("/// </summary>");
sb.AppendLine("public static class FluentIcons");
sb.AppendLine("{");

void EmitClass(string cls, List<(string Name, string Svg)> items, bool filledFlag)
{
    sb.AppendLine($"    /// <summary>{cls} (outline) Fluent icons.</summary>");
    sb.AppendLine($"    public static class {cls}");
    sb.AppendLine("    {");
    foreach (var (name, svg) in items)
    {
        sb.AppendLine($"        /// <summary>The Fluent <c>{name}</c> ({cls.ToLowerInvariant()}) icon.</summary>");
        sb.AppendLine($"        public static FlareFluentIcon {name} {{ get; }} = new() {{ Name = \"{name}\", Filled = {(filledFlag ? "true" : "false")}, Data = \"\"\"{svg}\"\"\" }};");
    }
    sb.AppendLine("    }");
}

EmitClass("Regular", regular, false);
sb.AppendLine();
EmitClass("Filled", filled, true);
sb.AppendLine("}");

var outPath = Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "..", "..",
    "src", "Flare.Icons.Fluent", "FluentIcons.g.cs"));
File.WriteAllText(outPath, sb.ToString());

Console.WriteLine($"Regular: {regular.Count}, Filled: {filled.Count}");
Console.WriteLine($"Missing (skipped): {(missing.Count == 0 ? "(none)" : string.Join(", ", missing))}");
Console.WriteLine($"Wrote {outPath}");
