using System.Reflection;
using System.Text;

// Generates a curated FluentUIIcons catalog for Flare.Icons.FluentUI.Svg from the real Microsoft Fluent UI System
// Icons package (Regular + Filled, Size24). Over-list names freely: any not present in a variant is skipped
// and reported, so the output only contains icons that genuinely exist.

var regularAsm = typeof(Microsoft.FluentUI.AspNetCore.Components.Icons.Regular.Size24.Home).Assembly;
var filledAsm = typeof(Microsoft.FluentUI.AspNetCore.Components.Icons.Filled.Size24.Home).Assembly;

const string regularPrefix = "Microsoft.FluentUI.AspNetCore.Components.Icons.Regular.Size24+";
const string filledPrefix = "Microsoft.FluentUI.AspNetCore.Components.Icons.Filled.Size24+";

// Enumerate EVERY Size24 icon in a variant assembly (instantiate, read the SVG Content).
List<(string Name, string Svg)> Enumerate(Assembly asm, string prefix)
{
    var result = new List<(string, string)>();
    foreach (var t in asm.GetTypes())
    {
        if (t.FullName is null || !t.FullName.StartsWith(prefix, StringComparison.Ordinal)) continue;
        if (!t.IsClass || t.IsAbstract) continue;
        var ctor = t.GetConstructor(Type.EmptyTypes);
        var contentProp = t.GetProperty("Content");
        if (ctor is null || contentProp is null) continue;
        object inst;
        try { inst = ctor.Invoke(null); } catch { continue; }
        if (contentProp.GetValue(inst) is not string svg || svg.Length == 0) continue;
        result.Add((t.Name, svg));
    }
    return result.OrderBy(x => x.Item1, StringComparer.Ordinal).ToList();
}

var regular = Enumerate(regularAsm, regularPrefix);
var filled = Enumerate(filledAsm, filledPrefix);
var missing = new List<string>();

var sb = new StringBuilder();
sb.AppendLine("// <auto-generated />");
sb.AppendLine("// Generated by tools/FluentIconGen from Microsoft.FluentUI.AspNetCore.Components.Icons (Size24).");
sb.AppendLine("// Fluent UI System Icons are (c) Microsoft, MIT licensed. Re-run the tool to refresh/extend.");
sb.AppendLine();
sb.AppendLine("namespace Flare.Components;");
sb.AppendLine();
sb.AppendLine("/// <summary>");
sb.AppendLine("/// A curated set of common Fluent UI System Icons (Size 24), ready as <see cref=\"FlareFluentUIIcon\"/>");
sb.AppendLine("/// values. Use anywhere a <see cref=\"FlareIcon\"/> is accepted, e.g.");
sb.AppendLine("/// <c>&lt;FlareIconButton Icon=\"@FluentUIIcons.Regular.Home\" /&gt;</c>. For icons not in this set, pass the");
sb.AppendLine("/// SVG path from the Fluent assets directly via <see cref=\"FlareFluentUIIcon.Data\"/>.");
sb.AppendLine("/// </summary>");
sb.AppendLine("public static class FluentUIIcons");
sb.AppendLine("{");

void EmitClass(string cls, List<(string Name, string Svg)> items, bool filledFlag)
{
    sb.AppendLine($"    /// <summary>{cls} (outline) Fluent icons.</summary>");
    sb.AppendLine($"    public static class {cls}");
    sb.AppendLine("    {");
    foreach (var (name, svg) in items)
    {
        sb.AppendLine($"        /// <summary>The Fluent <c>{name}</c> ({cls.ToLowerInvariant()}) icon.</summary>");
        // Expression-bodied (computed) so a full catalog does not build a pathological static constructor.
        sb.AppendLine($"        public static FlareFluentUIIcon {name} => new() {{ Name = \"{name}\", Filled = {(filledFlag ? "true" : "false")}, Data = \"\"\"{svg}\"\"\" }};");
    }
    sb.AppendLine("    }");
}

EmitClass("Regular", regular, false);
sb.AppendLine();
EmitClass("Filled", filled, true);
sb.AppendLine("}");

var outPath = Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "..", "..",
    "src", "Flare.Icons.FluentUI.Svg", "FluentUIIcons.g.cs"));
File.WriteAllText(outPath, sb.ToString());

Console.WriteLine($"Regular: {regular.Count}, Filled: {filled.Count}");
Console.WriteLine($"Missing (skipped): {(missing.Count == 0 ? "(none)" : string.Join(", ", missing))}");
Console.WriteLine($"Wrote {outPath}");
