//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flare.Components.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FlareStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FlareStrings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Flare.Components.Resources.FlareStrings", typeof(FlareStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close.
        /// </summary>
        public static string Alert_Close {
            get {
                return ResourceManager.GetString("Alert_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close tab.
        /// </summary>
        public static string Aria_CloseTab {
            get {
                return ResourceManager.GetString("Aria_CloseTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loading.
        /// </summary>
        public static string Aria_Loading {
            get {
                return ResourceManager.GetString("Aria_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Toggle drawer.
        /// </summary>
        public static string Aria_ToggleDrawer {
            get {
                return ResourceManager.GetString("Aria_ToggleDrawer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Toggle password visibility.
        /// </summary>
        public static string Aria_TogglePassword {
            get {
                return ResourceManager.GetString("Aria_TogglePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} more.
        /// </summary>
        public static string Avatar_OverflowMore {
            get {
                return ResourceManager.GetString("Avatar_OverflowMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show hidden breadcrumbs.
        /// </summary>
        public static string Breadcrumb_Expand {
            get {
                return ResourceManager.GetString("Breadcrumb_Expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Next month.
        /// </summary>
        public static string Calendar_NextMonth {
            get {
                return ResourceManager.GetString("Calendar_NextMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Previous month.
        /// </summary>
        public static string Calendar_PrevMonth {
            get {
                return ResourceManager.GetString("Calendar_PrevMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Go to slide {0}.
        /// </summary>
        public static string Carousel_GoToSlide {
            get {
                return ResourceManager.GetString("Carousel_GoToSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Carousel.
        /// </summary>
        public static string Carousel_Label {
            get {
                return ResourceManager.GetString("Carousel_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Next slide.
        /// </summary>
        public static string Carousel_Next {
            get {
                return ResourceManager.GetString("Carousel_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Previous slide.
        /// </summary>
        public static string Carousel_Prev {
            get {
                return ResourceManager.GetString("Carousel_Prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete chip.
        /// </summary>
        public static string Chip_Delete {
            get {
                return ResourceManager.GetString("Chip_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copied!.
        /// </summary>
        public static string Clipboard_Copied {
            get {
                return ResourceManager.GetString("Clipboard_Copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copy to clipboard.
        /// </summary>
        public static string Clipboard_Copy {
            get {
                return ResourceManager.GetString("Clipboard_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Custom.
        /// </summary>
        public static string ColorCustomizer_Custom {
            get {
                return ResourceManager.GetString("ColorCustomizer_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Theme Color.
        /// </summary>
        public static string ColorCustomizer_Label {
            get {
                return ResourceManager.GetString("ColorCustomizer_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset.
        /// </summary>
        public static string ColorCustomizer_Reset {
            get {
                return ResourceManager.GetString("ColorCustomizer_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pick color.
        /// </summary>
        public static string ColorPicker_EyeDropperLabel {
            get {
                return ResourceManager.GetString("ColorPicker_EyeDropperLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pick color from screen.
        /// </summary>
        public static string ColorPicker_EyeDropperTitle {
            get {
                return ResourceManager.GetString("ColorPicker_EyeDropperTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Color picker.
        /// </summary>
        public static string ColorPicker_Label {
            get {
                return ResourceManager.GetString("ColorPicker_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add condition.
        /// </summary>
        public static string DataGrid_AddCondition {
            get {
                return ResourceManager.GetString("DataGrid_AddCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add group.
        /// </summary>
        public static string DataGrid_AddGroup {
            get {
                return ResourceManager.GetString("DataGrid_AddGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на And.
        /// </summary>
        public static string DataGrid_And {
            get {
                return ResourceManager.GetString("DataGrid_And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} results.
        /// </summary>
        public static string DataGrid_AnnounceFiltered {
            get {
                return ResourceManager.GetString("DataGrid_AnnounceFiltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Page {0} of {1}.
        /// </summary>
        public static string DataGrid_AnnouncePage {
            get {
                return ResourceManager.GetString("DataGrid_AnnouncePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sorted by {0}, ascending.
        /// </summary>
        public static string DataGrid_AnnounceSortAsc {
            get {
                return ResourceManager.GetString("DataGrid_AnnounceSortAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sorting cleared.
        /// </summary>
        public static string DataGrid_AnnounceSortCleared {
            get {
                return ResourceManager.GetString("DataGrid_AnnounceSortCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sorted by {0}, descending.
        /// </summary>
        public static string DataGrid_AnnounceSortDesc {
            get {
                return ResourceManager.GetString("DataGrid_AnnounceSortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apply.
        /// </summary>
        public static string DataGrid_ApplyFilters {
            get {
                return ResourceManager.GetString("DataGrid_ApplyFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string DataGrid_Cancel {
            get {
                return ResourceManager.GetString("DataGrid_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear.
        /// </summary>
        public static string DataGrid_ClearFilter {
            get {
                return ResourceManager.GetString("DataGrid_ClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear all.
        /// </summary>
        public static string DataGrid_ClearFilters {
            get {
                return ResourceManager.GetString("DataGrid_ClearFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Columns.
        /// </summary>
        public static string DataGrid_ColumnsLabel {
            get {
                return ResourceManager.GetString("DataGrid_ColumnsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Configure filtering.
        /// </summary>
        public static string DataGrid_ConfigureFilters {
            get {
                return ResourceManager.GetString("DataGrid_ConfigureFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        public static string DataGrid_Edit {
            get {
                return ResourceManager.GetString("DataGrid_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Export to CSV.
        /// </summary>
        public static string DataGrid_ExportCsv {
            get {
                return ResourceManager.GetString("DataGrid_ExportCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Export to Excel.
        /// </summary>
        public static string DataGrid_ExportExcel {
            get {
                return ResourceManager.GetString("DataGrid_ExportExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Export to JSON.
        /// </summary>
        public static string DataGrid_ExportJson {
            get {
                return ResourceManager.GetString("DataGrid_ExportJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Export to TSV.
        /// </summary>
        public static string DataGrid_ExportTsv {
            get {
                return ResourceManager.GetString("DataGrid_ExportTsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filter.
        /// </summary>
        public static string DataGrid_Filter {
            get {
                return ResourceManager.GetString("DataGrid_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filter….
        /// </summary>
        public static string DataGrid_FilterPlaceholder {
            get {
                return ResourceManager.GetString("DataGrid_FilterPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Preset filter.
        /// </summary>
        public static string DataGrid_FilterPresets {
            get {
                return ResourceManager.GetString("DataGrid_FilterPresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Value.
        /// </summary>
        public static string DataGrid_FilterValue {
            get {
                return ResourceManager.GetString("DataGrid_FilterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на and.
        /// </summary>
        public static string DataGrid_FilterValue2 {
            get {
                return ResourceManager.GetString("DataGrid_FilterValue2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loading….
        /// </summary>
        public static string DataGrid_Loading {
            get {
                return ResourceManager.GetString("DataGrid_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на More export options.
        /// </summary>
        public static string DataGrid_MoreExports {
            get {
                return ResourceManager.GetString("DataGrid_MoreExports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No data.
        /// </summary>
        public static string DataGrid_NoData {
            get {
                return ResourceManager.GetString("DataGrid_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (No filter).
        /// </summary>
        public static string DataGrid_NoFilter {
            get {
                return ResourceManager.GetString("DataGrid_NoFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на is between.
        /// </summary>
        public static string DataGrid_OpBetween {
            get {
                return ResourceManager.GetString("DataGrid_OpBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на contains.
        /// </summary>
        public static string DataGrid_OpContains {
            get {
                return ResourceManager.GetString("DataGrid_OpContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ends with.
        /// </summary>
        public static string DataGrid_OpEndsWith {
            get {
                return ResourceManager.GetString("DataGrid_OpEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на equals.
        /// </summary>
        public static string DataGrid_OpEquals {
            get {
                return ResourceManager.GetString("DataGrid_OpEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на greater or equal.
        /// </summary>
        public static string DataGrid_OpGreaterOrEqual {
            get {
                return ResourceManager.GetString("DataGrid_OpGreaterOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на greater than.
        /// </summary>
        public static string DataGrid_OpGreaterThan {
            get {
                return ResourceManager.GetString("DataGrid_OpGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на is any of.
        /// </summary>
        public static string DataGrid_OpIn {
            get {
                return ResourceManager.GetString("DataGrid_OpIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на is not null.
        /// </summary>
        public static string DataGrid_OpIsNotNull {
            get {
                return ResourceManager.GetString("DataGrid_OpIsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на is null.
        /// </summary>
        public static string DataGrid_OpIsNull {
            get {
                return ResourceManager.GetString("DataGrid_OpIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на less or equal.
        /// </summary>
        public static string DataGrid_OpLessOrEqual {
            get {
                return ResourceManager.GetString("DataGrid_OpLessOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на less than.
        /// </summary>
        public static string DataGrid_OpLessThan {
            get {
                return ResourceManager.GetString("DataGrid_OpLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на is not between.
        /// </summary>
        public static string DataGrid_OpNotBetween {
            get {
                return ResourceManager.GetString("DataGrid_OpNotBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на not equals.
        /// </summary>
        public static string DataGrid_OpNotEquals {
            get {
                return ResourceManager.GetString("DataGrid_OpNotEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на is none of.
        /// </summary>
        public static string DataGrid_OpNotIn {
            get {
                return ResourceManager.GetString("DataGrid_OpNotIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на starts with.
        /// </summary>
        public static string DataGrid_OpStartsWith {
            get {
                return ResourceManager.GetString("DataGrid_OpStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Or.
        /// </summary>
        public static string DataGrid_Or {
            get {
                return ResourceManager.GetString("DataGrid_Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove condition.
        /// </summary>
        public static string DataGrid_RemoveCondition {
            get {
                return ResourceManager.GetString("DataGrid_RemoveCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove group.
        /// </summary>
        public static string DataGrid_RemoveGroup {
            get {
                return ResourceManager.GetString("DataGrid_RemoveGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rows:.
        /// </summary>
        public static string DataGrid_RowsLabel {
            get {
                return ResourceManager.GetString("DataGrid_RowsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string DataGrid_Save {
            get {
                return ResourceManager.GetString("DataGrid_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search.
        /// </summary>
        public static string DataGrid_Search {
            get {
                return ResourceManager.GetString("DataGrid_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (Select all).
        /// </summary>
        public static string DataGrid_SelectAll {
            get {
                return ResourceManager.GetString("DataGrid_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show/hide columns.
        /// </summary>
        public static string DataGrid_ToggleColumns {
            get {
                return ResourceManager.GetString("DataGrid_ToggleColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Today.
        /// </summary>
        public static string DatePicker_Today {
            get {
                return ResourceManager.GetString("DatePicker_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на End date.
        /// </summary>
        public static string DateRangePicker_EndLabel {
            get {
                return ResourceManager.GetString("DateRangePicker_EndLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Last 30 days.
        /// </summary>
        public static string DateRangePicker_Last30Days {
            get {
                return ResourceManager.GetString("DateRangePicker_Last30Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Last 7 days.
        /// </summary>
        public static string DateRangePicker_Last7Days {
            get {
                return ResourceManager.GetString("DateRangePicker_Last7Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Last month.
        /// </summary>
        public static string DateRangePicker_LastMonth {
            get {
                return ResourceManager.GetString("DateRangePicker_LastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start date.
        /// </summary>
        public static string DateRangePicker_StartLabel {
            get {
                return ResourceManager.GetString("DateRangePicker_StartLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This month.
        /// </summary>
        public static string DateRangePicker_ThisMonth {
            get {
                return ResourceManager.GetString("DateRangePicker_ThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This year.
        /// </summary>
        public static string DateRangePicker_ThisYear {
            get {
                return ResourceManager.GetString("DateRangePicker_ThisYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Today.
        /// </summary>
        public static string DateRangePicker_Today {
            get {
                return ResourceManager.GetString("DateRangePicker_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yesterday.
        /// </summary>
        public static string DateRangePicker_Yesterday {
            get {
                return ResourceManager.GetString("DateRangePicker_Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date.
        /// </summary>
        public static string DateTimePicker_DateTab {
            get {
                return ResourceManager.GetString("DateTimePicker_DateTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open date and time picker.
        /// </summary>
        public static string DateTimePicker_Open {
            get {
                return ResourceManager.GetString("DateTimePicker_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Time.
        /// </summary>
        public static string DateTimePicker_TimeTab {
            get {
                return ResourceManager.GetString("DateTimePicker_TimeTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string Dialog_Cancel {
            get {
                return ResourceManager.GetString("Dialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close.
        /// </summary>
        public static string Dialog_Close {
            get {
                return ResourceManager.GetString("Dialog_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirm.
        /// </summary>
        public static string Dialog_Confirm {
            get {
                return ResourceManager.GetString("Dialog_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OK.
        /// </summary>
        public static string Dialog_Ok {
            get {
                return ResourceManager.GetString("Dialog_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Accepted:.
        /// </summary>
        public static string DropZone_Accepted {
            get {
                return ResourceManager.GetString("DropZone_Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Drag &amp; drop files or click to browse.
        /// </summary>
        public static string DropZone_Browse {
            get {
                return ResourceManager.GetString("DropZone_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Drop files here.
        /// </summary>
        public static string DropZone_DropFiles {
            get {
                return ResourceManager.GetString("DropZone_DropFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File drop zone.
        /// </summary>
        public static string DropZone_Label {
            get {
                return ResourceManager.GetString("DropZone_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Empty.
        /// </summary>
        public static string EmptyState_Label {
            get {
                return ResourceManager.GetString("EmptyState_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No results.
        /// </summary>
        public static string Field_NoResults {
            get {
                return ResourceManager.GetString("Field_NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Accepted:.
        /// </summary>
        public static string FileUpload_Accepted {
            get {
                return ResourceManager.GetString("FileUpload_Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Drop files here or click to browse.
        /// </summary>
        public static string FileUpload_DropText {
            get {
                return ResourceManager.GetString("FileUpload_DropText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset.
        /// </summary>
        public static string FormBuilder_Reset {
            get {
                return ResourceManager.GetString("FormBuilder_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Submit.
        /// </summary>
        public static string FormBuilder_Submit {
            get {
                return ResourceManager.GetString("FormBuilder_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear.
        /// </summary>
        public static string Input_Clear {
            get {
                return ResourceManager.GetString("Input_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search….
        /// </summary>
        public static string MultiSelect_Search {
            get {
                return ResourceManager.GetString("MultiSelect_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select all.
        /// </summary>
        public static string MultiSelect_SelectAll {
            get {
                return ResourceManager.GetString("MultiSelect_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Back to top.
        /// </summary>
        public static string Nav_BackToTop {
            get {
                return ResourceManager.GetString("Nav_BackToTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bottom navigation.
        /// </summary>
        public static string Nav_BottomNavigation {
            get {
                return ResourceManager.GetString("Nav_BottomNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Breadcrumb.
        /// </summary>
        public static string Nav_Breadcrumb {
            get {
                return ResourceManager.GetString("Nav_Breadcrumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Navigation.
        /// </summary>
        public static string Nav_Navigation {
            get {
                return ResourceManager.GetString("Nav_Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pagination.
        /// </summary>
        public static string Nav_Pagination {
            get {
                return ResourceManager.GetString("Nav_Pagination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Decrement.
        /// </summary>
        public static string NumericField_Decrement {
            get {
                return ResourceManager.GetString("NumericField_Decrement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Increment.
        /// </summary>
        public static string NumericField_Increment {
            get {
                return ResourceManager.GetString("NumericField_Increment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на On this page.
        /// </summary>
        public static string OnThisPage_Title {
            get {
                return ResourceManager.GetString("OnThisPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Digit {0} of {1}.
        /// </summary>
        public static string OtpInput_CellLabel {
            get {
                return ResourceManager.GetString("OtpInput_CellLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на One-time password.
        /// </summary>
        public static string OtpInput_GroupLabel {
            get {
                return ResourceManager.GetString("OtpInput_GroupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на First page.
        /// </summary>
        public static string Pagination_First {
            get {
                return ResourceManager.GetString("Pagination_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Last page.
        /// </summary>
        public static string Pagination_Last {
            get {
                return ResourceManager.GetString("Pagination_Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Next page.
        /// </summary>
        public static string Pagination_Next {
            get {
                return ResourceManager.GetString("Pagination_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Page {0}.
        /// </summary>
        public static string Pagination_Page {
            get {
                return ResourceManager.GetString("Pagination_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Previous page.
        /// </summary>
        public static string Pagination_Prev {
            get {
                return ResourceManager.GetString("Pagination_Prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}–{1} of {2}.
        /// </summary>
        public static string Pagination_Range {
            get {
                return ResourceManager.GetString("Pagination_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string Picker_Cancel {
            get {
                return ResourceManager.GetString("Picker_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear.
        /// </summary>
        public static string Picker_Clear {
            get {
                return ResourceManager.GetString("Picker_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Next.
        /// </summary>
        public static string Picker_Next {
            get {
                return ResourceManager.GetString("Picker_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OK.
        /// </summary>
        public static string Picker_Ok {
            get {
                return ResourceManager.GetString("Picker_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Previous.
        /// </summary>
        public static string Picker_Previous {
            get {
                return ResourceManager.GetString("Picker_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rating.
        /// </summary>
        public static string Rating_Group {
            get {
                return ResourceManager.GetString("Rating_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} out of {1}.
        /// </summary>
        public static string Rating_Star {
            get {
                return ResourceManager.GetString("Rating_Star", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rich text editor.
        /// </summary>
        public static string RTE_Label {
            get {
                return ResourceManager.GetString("RTE_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start typing….
        /// </summary>
        public static string RTE_Placeholder {
            get {
                return ResourceManager.GetString("RTE_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Keyboard Shortcuts.
        /// </summary>
        public static string Shortcuts_Title {
            get {
                return ResourceManager.GetString("Shortcuts_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close.
        /// </summary>
        public static string Snackbar_Close {
            get {
                return ResourceManager.GetString("Snackbar_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Actions.
        /// </summary>
        public static string SpeedDial_Actions {
            get {
                return ResourceManager.GetString("SpeedDial_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Back.
        /// </summary>
        public static string Stepper_Back {
            get {
                return ResourceManager.GetString("Stepper_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Completed.
        /// </summary>
        public static string Stepper_Completed {
            get {
                return ResourceManager.GetString("Stepper_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string Stepper_Error {
            get {
                return ResourceManager.GetString("Stepper_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Next.
        /// </summary>
        public static string Stepper_Next {
            get {
                return ResourceManager.GetString("Stepper_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Progress steps.
        /// </summary>
        public static string Stepper_ProgressLabel {
            get {
                return ResourceManager.GetString("Stepper_ProgressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Step {0}.
        /// </summary>
        public static string Stepper_Step {
            get {
                return ResourceManager.GetString("Stepper_Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scroll tabs backward.
        /// </summary>
        public static string Tabs_ScrollBack {
            get {
                return ResourceManager.GetString("Tabs_ScrollBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scroll tabs forward.
        /// </summary>
        public static string Tabs_ScrollForward {
            get {
                return ResourceManager.GetString("Tabs_ScrollForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove.
        /// </summary>
        public static string TagInput_Remove {
            get {
                return ResourceManager.GetString("TagInput_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Switch to dark mode.
        /// </summary>
        public static string Theme_ToggleDark {
            get {
                return ResourceManager.GetString("Theme_ToggleDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Switch to light mode.
        /// </summary>
        public static string Theme_ToggleLight {
            get {
                return ResourceManager.GetString("Theme_ToggleLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Time.
        /// </summary>
        public static string TimePicker_FieldLabel {
            get {
                return ResourceManager.GetString("TimePicker_FieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select time.
        /// </summary>
        public static string TimePicker_Headline {
            get {
                return ResourceManager.GetString("TimePicker_Headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hours.
        /// </summary>
        public static string TimePicker_Hours {
            get {
                return ResourceManager.GetString("TimePicker_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minutes.
        /// </summary>
        public static string TimePicker_Minutes {
            get {
                return ResourceManager.GetString("TimePicker_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open time picker.
        /// </summary>
        public static string TimePicker_Open {
            get {
                return ResourceManager.GetString("TimePicker_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Move all to source.
        /// </summary>
        public static string Transfer_MoveAllToSource {
            get {
                return ResourceManager.GetString("Transfer_MoveAllToSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Move all to target.
        /// </summary>
        public static string Transfer_MoveAllToTarget {
            get {
                return ResourceManager.GetString("Transfer_MoveAllToTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Move selected to source.
        /// </summary>
        public static string Transfer_MoveToSource {
            get {
                return ResourceManager.GetString("Transfer_MoveToSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Move selected to target.
        /// </summary>
        public static string Transfer_MoveToTarget {
            get {
                return ResourceManager.GetString("Transfer_MoveToTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Collapse.
        /// </summary>
        public static string Tree_Collapse {
            get {
                return ResourceManager.GetString("Tree_Collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Expand.
        /// </summary>
        public static string Tree_Expand {
            get {
                return ResourceManager.GetString("Tree_Expand", resourceCulture);
            }
        }
    }
}
