using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Text;
using System.Text.RegularExpressions;

namespace Flare.Gallery.Generators;

[Generator]
public class SnippetGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var demoFiles = context.AdditionalTextsProvider
            .Where(file => Path.GetFileName(file.Path).Contains("Demo."));

        var fileContents = demoFiles.Select((file, cancellationToken) =>
        {
            var path = file.Path;
            var name = Path.GetFileName(path);
            var text = file.GetText(cancellationToken)?.ToString() ?? "";
            return (Path: path, Name: name, Text: text);
        });

        var collectedFiles = fileContents.Collect();

        context.RegisterSourceOutput(collectedFiles, (spc, files) =>
        {
            var registryCode = BuildRegistryClass(files);
            spc.AddSource("DemoCodeRegistry.g.cs", SourceText.From(registryCode, Encoding.UTF8));
        });
    }

    private static string BuildRegistryClass(System.Collections.Immutable.ImmutableArray<(string Path, string Name, string Text)> files)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine("namespace Flare.Gallery.Components.Shared;");
        sb.AppendLine();
        sb.AppendLine("public static class DemoCodeRegistry");
        sb.AppendLine("{");
        sb.AppendLine("    private static readonly Dictionary<string, List<CodeTab>> _registry = new Dictionary<string, List<CodeTab>>()");
        sb.AppendLine("    {");

        var grouped = files.GroupBy(f => f.Name.Substring(0, f.Name.IndexOf('.')));

        foreach (var group in grouped)
        {
            var componentName = group.Key;

            // Временные переменные для хранения вкладок текущего демо-компонента
            string? razorCode = null;
            string? csharpCode = null;
            string? cssCode = null;
            string? jsonCode = null;

            foreach (var file in group)
            {
                string fullName = file.Name;
                string ext = fullName.Substring(componentName.Length + 1).ToLower();
                string text = file.Text;

                if (ext == "razor")
                {
                    razorCode = text;

                    // Если отдельного .cs файла нет, пробуем вытащить @code из .razor
                    // Ищем паттерн: @code { ... все что внутри ... }
                    var codeMatch = Regex.Match(text, @"@code\s*\{(.*)\}", RegexOptions.Singleline);
                    if (codeMatch.Success && string.IsNullOrEmpty(csharpCode))
                    {
                        csharpCode = FixIndents(codeMatch.Groups[1].Value.Trim());
                    }
                }
                else if (ext == "razor.cs")
                {
                    // Если есть физический .razor.cs файл, он в приоритете
                    var classMatch = Regex.Match(text, @"class\s+\w+\s*\{(.*)\}\s*\}?\s*$", RegexOptions.Singleline);
                    csharpCode = classMatch.Success ? classMatch.Groups[1].Value.Trim() : text;
                    csharpCode = FixIndents(csharpCode);
                }
                else if (ext == "razor.css")
                {
                    cssCode = text;
                }
                else if (ext == "json")
                {
                    jsonCode = text;
                }
            }

            // Начинаем запись блока вкладок для компонента
            sb.AppendLine($"        {{ \"{componentName}\", new List<CodeTab> {{");

            if (!string.IsNullOrEmpty(razorCode))
            {
                sb.AppendLine("            new CodeTab { ");
                sb.AppendLine("                Title = \"Razor\", ");
                sb.AppendLine("                Language = \"razor\", ");
                sb.AppendLine($"                Code = @\"{razorCode!.Replace("\"", "\"\"")}\" ");
                sb.AppendLine("            },");
            }

            if (!string.IsNullOrEmpty(csharpCode))
            {
                sb.AppendLine("            new CodeTab { ");
                sb.AppendLine("                Title = \"C#\", ");
                sb.AppendLine("                Language = \"csharp\", ");
                sb.AppendLine($"                Code = @\"{csharpCode!.Replace("\"", "\"\"")}\" ");
                sb.AppendLine("            },");
            }

            if (!string.IsNullOrEmpty(cssCode))
            {
                sb.AppendLine("            new CodeTab { ");
                sb.AppendLine("                Title = \"CSS\", ");
                sb.AppendLine("                Language = \"css\", ");
                sb.AppendLine($"                Code = @\"{cssCode!.Replace("\"", "\"\"")}\" ");
                sb.AppendLine("            },");
            }

            if (!string.IsNullOrEmpty(jsonCode))
            {
                sb.AppendLine("            new CodeTab { ");
                sb.AppendLine("                Title = \"JSON\", ");
                sb.AppendLine("                Language = \"json\", ");
                sb.AppendLine($"                Code = @\"{jsonCode!.Replace("\"", "\"\"")}\" ");
                sb.AppendLine("            },");
            }

            sb.AppendLine("        } },");
        }

        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("    public static List<CodeTab> GetTabs(string componentName)");
        sb.AppendLine("    {");
        sb.AppendLine("        return _registry.TryGetValue(componentName, out var tabs) ? tabs : new List<CodeTab>();");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string FixIndents(string code)
    {
        var lines = code.Split(new[] { "\r\n", "\n", "\r" }, StringSplitOptions.None);

        var nonBlocks = new List<string>();
        foreach (var line in lines)
        {
            if (!string.IsNullOrEmpty(line) && line.Trim().Length > 0)
            {
                nonBlocks.Add(line);
            }
        }

        if (nonBlocks.Count == 0) return code;

        int minIndent = int.MaxValue;
        foreach (var line in nonBlocks)
        {
            int indent = 0;
            foreach (char c in line)
            {
                if (c == ' ') indent++;
                else if (c == '\t') indent += 4;
                else break;
            }
            if (indent < minIndent) minIndent = indent;
        }

        var cleanedLines = new List<string>();
        foreach (var l in lines)
        {
            cleanedLines.Add(l.Length >= minIndent ? l.Substring(minIndent) : l);
        }

        return string.Join("\n", cleanedLines.ToArray()).Trim();
    }
}
